name: Android Firebase App Distribution PushToTesters

on:
  push:
    branches:
      - main

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Verify target files
        run: |
          test -f lib/main_production.dart || { echo "Target file lib/main_production.dart not found"; exit 1; }
          test -f lib/main_development.dart || { echo "Target file lib/main_development.dart not found"; exit 1; }

      - name: Build APKs
        run: |
          flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons
      
      - name: List APK files
        run: |
          ls build/app/outputs/flutter-apk

      - name: Upload artifact to Firebase App Distribution - Production
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.APP_ID}} 
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: All testers
          file: build/app/outputs/flutter-apk/app-production-release.apk
